[project]
name = "tsf-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.3",
]
